# -*- coding: utf-8 -*-
"""categorisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTdS59FRLTY9Ie_QDfo6YIfX3s3c4PZo

# Searching for the category
"""

import pandas as pd

# products_cl.csv
url = "https://drive.google.com/file/d/1s7Lai4NSlsYjGEPg1QSOUJobNYVsZBOJ/view?usp=sharing" 
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products_cl = pd.read_csv(path)

category_type_df = products_cl.copy()

pd.set_option('display.max_rows', 1000)
pd.set_option("display.max_colwidth", 200)

category_type_df.to_csv('category_type.csv')

category_type_df.category = category_type_df.category.fillna('Others')

category_type_df.loc[category_type_df['type'].isin(['11935397','57445397','12655397','1364']), "category"] = "External/storage Device"

category_type_df.loc[category_type_df['type'].isin(["12585395",'1298', '1229','1216','24215399','5720','8696','42945397',
                                                    '13555403','11905404','1515','12575403','13005399','12085400',
                                                    '1276','5399','21535407','1231','13615399','5405','2449','5395',
                                                    '12355400','1416','10142','14365395','14035403','1387',
                                                    '10230',"5398", '5384','24885185','24215399','1230','1325','2434']), "category"] = "Apple Accessories"

category_type_df.loc[category_type_df['type'].isin(['11865403','12635403','13835403',"5,49E+11",'5403']), "category"] = "Gadget case"

category_type_df.loc[category_type_df['type'].isin(["1,02E+12",'2158',"5,39E+11",'1282','9,29E+11','2,17E+11','21632158']), "category"] = "New/Refurbished Macbook"

category_type_df.loc[category_type_df["type"].isin (["1433",'12215397','14305406','12995397','12755395']),'category']=  'Installation/Expansion/Upgrade kit'

category_type_df.loc[category_type_df["type"].isin(["5,74E+15","2,16E+11",'118692158','5,43E+15','51882158',"11821715",'13621714',
                                                    '51871714','12141714','106431714','1714',
                                                    '51861714',"51601716",'85651716','24811716',
                       '113281716','113291716','85641716','1716','24821716','24895185']),'category'] = 'iMac,' ' ipod,' ' ipad' ',  iphones' ', iwatch'

category_type_df.loc[category_type_df["type"] == "1296",'category':] = 'Monitors'

category_type_df.loc[category_type_df["type"] == "9094" ,"category" :] = 'Surveillance cameras'

category_type_df.loc[category_type_df["type"] == "1392", "category" :] = 'Back packs'

category_type_df.loc[category_type_df["type"].isin(["1,44E+11", '20642062']), "category" :] = 'Repair Services'

category_type_df.loc[category_type_df["type"] == "12175397", "category" :] = 'Servers'

category_type_df.loc[category_type_df["type"].isin(["13855401", '54025401','5401','1405']), "category":] = 'tablet & keyboard & accessories'

category_type_df.loc[category_type_df["type"].isin(["5404", '1375']), 'category':] = 'Miscellaneous gadgets'

54085407
category_type_df.loc[category_type_df["type"].isin(["54085407",'1424','101781405','21485407','12645406']), 'category':] = 'Replacement parts & tools'

category_type_df.loc[category_type_df["type"] == "1334", "category" :] = 'Router'

category_type_df['category'].isna().sum()

category_type_df.category.value_counts()

from google.colab import files
#category_type_df.to_csv('category_type.csv', index=False)
#files.download("category_type.csv")